version: '2'
services:
  githubissueseebook:
    image: knarfeh/githubissues2ebook
    build: .
    volumes:
      - .:/src
    environment:
      - URL=https://github.com/olebedev/go-starter-kit/issues
        #- QUERY_STRING=state=open
      - DAY_TIME_STAMP=2018-07-23
      - ES_HOST_PORT=http://192.168.199.121:9200
      - INCLUDE_COMMENTS=true
    env_file:
      - envs/secret.env
    networks:
      - githubissues2ebook

networks:
  githubissues2ebook:
    driver: bridge
